### PR TITLE
Update package URL

### PR DESCRIPTION
**Pull request by BoboTiG**

### CODE REVIEW

**Comment by xoviat** [comment]
This is not something that is actually going to make it to pypi for a long time.

**Comment by BoboTiG** [comment]
Perhaps that link would be better if you want to redirect users to up-to-date packages: https://sourceforge.net/projects/pywin32/ ? Because the current one does not exist.
I can update the patch if you are OK.

**Comment by xoviat** [comment]
The point is that these changes will not make it to pypi for a long time, if ever.

**Comment by BoboTiG** [comment]
Oh! OK, I get it!
Sorry for the noise :)

**Pull request closed without merging**
